### PR TITLE
WOULD NOT UNDERSTAND IF THEY WATCHED ME DO WHAT I DO.

### PR DESCRIPTION
**Pull request by BSCPGROUPHOLDINGSLLC**
## STFGX & BRK-B
*** NOV 13, 2021
[FILED NOVEMBER 13, 2021](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792695/_TCRReport.pdf)

*** ATTACHMENTS
[111 Docket 2.3.1-LEGAL.pdf](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792697/111.Docket.2.3.1-LEGAL.pdf)

IMG_7161

IMG_7161_E

IMG_7161-b

*** DEC 19, 2021
[Date December 19, 2021 NYS 240.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792703/Date.December.19.2021.NYS.240.PDF)

*** DEC 19, 2021
[Sun, Dec 19, 2021 - GIVE ME BACK THE SEX TAPES AND ILL STOP.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792704/Sun.Dec.19.2021.-.GIVE.ME.BACK.THE.SEX.TAPES.AND.ILL.STOP.PDF)

*** DEC 19, 2021
[Sun, Dec 19, 2021 - give me my sex tapes back.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792705/Sun.Dec.19.2021.-.give.me.my.sex.tapes.back.PDF)

*** DEC 19, 2021
[Sun, Dec 19, 2021 240.65.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792706/Sun.Dec.19.2021.240.65.PDF)

IMG_7163

IMG_7163_A

IMG_7446

IMG_7446_D

IMG_7446_G

IMG_7160

IMG_7160_C

IMG_7160_F

*** MAY 27, 2022
[2022-05-27---TCRReport 16537-714-487-492.pdf](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792708/2022-05-27---TCRReport.16537-714-487-492.pdf)

### CODE REVIEW

**Comment by 153974-HSI-OXLEY-BANKS-40ACT** [comment]
https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/pull/1

**Comment by 153974-HSI-OXLEY-BANKS-40ACT** [comment]
Under USC 18.225.each person:

'...imprisoned for a term of not less than 10 years and which may be life."

https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/blob/BSCPGROUPHOLDINGSLLC-EMAIL-DOCKETS/ms-pwc-dicker

Those papers confer a violation of the Sarbanes-Oxley 2002 Rev.
-- questions?
/S/ BO DINCER.

On Sun, Aug 7, 2022 at 7:52 AM, Bo Dincer
<bo.dincer@yahoo.com> wrote:

I look up case number 153974/2020
- I don’t see any order from the Judge and can’t find anything in the Federal LOC system either.

Filed on August 4th, 2020. All papers to satisfy this breach which has a MINIMUM 10-YEAR SENTENCE.


18 U.S. Code § 225 - Continuing financial crimes enterprise.
(a) Whoever—
(1) organizes, manages, or supervises a continuing financial crimes enterprise; and
(2) receives $5,000,000 or more in gross receipts from such enterprise during any 24-month period,
shall be fined not more than $10,000,000 if an individual, or $20,000,000 if an organization, and imprisoned for a term of not less than 10 years and which may be life.
(b) For purposes of subsection (a), the term “continuing financial crimes enterprise” means a series of violations under section 215, 656, 657, 1005, 1006, 1007, 1014, 1032, or 1344 of this title, or section 1341 or 1343 affecting a financial institution, committed by at least 4 persons acting in concert.

Here’s a link to help you find the minx. 

https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/tree/BSCPGROUPHOLDINGSLLC-EMAIL-DOCKET

/S/ BO DINCER

On Sun, Aug 7, 2022 at 7:47 AM, Bo Dincer
<bo.dincer@yahoo.com> wrote:

SAMSUNG GALAXY 10 MAC ADDRESS

image
image
[SAMSUNG NOT PRE-CLEARED AT ANY TIME PRIOR TO JULY 10TH 2022 FOR" casual wire taps without consent " ](https://github.com/153974-HSI-OXLEY-BANKS-40ACT/153974-HSI-O

@153974-HSI-OXLEY-BANKS-40ACT 
@153974-HSI-OXLEY-BANKS-40ACT

**Comment by 153974-HSI-OXLEY-BANKS-40ACT** [comment]
> ## TRUST ME, THEY ARE STILL TRYING TO UNDERSTANDING THE CAUSE FOR CONTANGO.
> ## STFGX & BRK-B
> *** NOV 13, 2021
> [FILED NOVEMBER 13, 2021](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792695/_TCRReport.pdf)
> 
> 
> *** ATTACHMENTS
> [111 Docket 2.3.1-LEGAL.pdf](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792697/111.Docket.2.3.1-LEGAL.pdf)
> 
> IMG_7161
> 
> 
> IMG_7161_E
> 
> 
> IMG_7161-b
> 
> 
> *** DEC 19, 2021
> [Date December 19, 2021 NYS 240.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792703/Date.December.19.2021.NYS.240.PDF)
> 
> *** DEC 19, 2021
> [Sun, Dec 19, 2021 - GIVE ME BACK THE SEX TAPES AND ILL STOP.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792704/Sun.Dec.19.2021.-.GIVE.ME.BACK.THE.SEX.TAPES.AND.ILL.STOP.PDF)
> 
> *** DEC 19, 2021
> [Sun, Dec 19, 2021 - give me my sex tapes back.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792705/Sun.Dec.19.2021.-.give.me.my.sex.tapes.back.PDF)
> 
> *** DEC 19, 2021
> [Sun, Dec 19, 2021 240.65.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792706/Sun.Dec.19.2021.240.65.PDF)
> 
> IMG_7163
> 
> 
> IMG_7163_A
> 
> 
> IMG_7446
> 
> 
> IMG_7446_D
> 
> 
> IMG_7446_G
> 
> 
> IMG_7160
> 
> 
> IMG_7160_C
> 
> 
> IMG_7160_F
> 
> *** MAY 27, 2022
> [2022-05-27---TCRReport 16537-714-487-492.pdf](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792708/2022-05-27---TCRReport.16537-714-487-492.pdf)
> 
> 
> 

@153974-HSI-OXLEY-BANKS-40ACT 
@BSCPGROUPHOLDINGSLLC

**Comment by 153974-HSI-OXLEY-BANKS-40ACT** [comment]
The grrater of $852,029,489.38 lost in a day, and no CORPACT what are they holding???

@BSCPGROUPHOLDINGSLLC 
@153974-HSI-OXLEY-BANKS-40ACT

**Comment by BBO-IC3-HIT** [comment]
@BSCPGROUPHOLDINGSLLC 
@153974-HSI-OXLEY-BANKS-40ACT 

image

**Comment by 153974-HSI-OXLEY-BANKS-40ACT** [comment]
> ## TRUST ME, THEY ARE STILL TRYING TO UNDERSTANDING THE CAUSE FOR CONTANGO.
> ## STFGX & BRK-B
> *** NOV 13, 2021
> [FILED NOVEMBER 13, 2021](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792695/_TCRReport.pdf)
> 
> 
> *** ATTACHMENTS
> [111 Docket 2.3.1-LEGAL.pdf](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792697/111.Docket.2.3.1-LEGAL.pdf)
> 
> IMG_7161
> 
> 
> IMG_7161_E
> 
> 
> IMG_7161-b
> 
> 
> *** DEC 19, 2021
> [Date December 19, 2021 NYS 240.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792703/Date.December.19.2021.NYS.240.PDF)
> 
> *** DEC 19, 2021
> [Sun, Dec 19, 2021 - GIVE ME BACK THE SEX TAPES AND ILL STOP.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792704/Sun.Dec.19.2021.-.GIVE.ME.BACK.THE.SEX.TAPES.AND.ILL.STOP.PDF)
> 
> *** DEC 19, 2021
> [Sun, Dec 19, 2021 - give me my sex tapes back.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792705/Sun.Dec.19.2021.-.give.me.my.sex.tapes.back.PDF)
> 
> *** DEC 19, 2021
> [Sun, Dec 19, 2021 240.65.PDF](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792706/Sun.Dec.19.2021.240.65.PDF)
> 
> IMG_7163
> 
> 
> IMG_7163_A
> 
> 
> IMG_7446
> 
> 
> IMG_7446_D
> 
> 
> IMG_7446_G
> 
> 
> IMG_7160
> 
> 
> IMG_7160_C
> 
> 
> IMG_7160_F
> 
> *** MAY 27, 2022
> [2022-05-27---TCRReport 16537-714-487-492.pdf](https://github.com/BSCPGROUPHOLDINGSLLC/2021-DUCKER-ZUCKER/files/8792708/2022-05-27---TCRReport.16537-714-487-492.pdf)
> 
> 
> 

# ACCESSORY PEEPING TOMS




@BSCPGROUPHOLDINGSLLC 

@153974-HSI-OXLEY-BANKS-40ACT 

@BBO-IC3-HIT

**Pull request closed without merging**
